### ISSUE TITLE
Feature Request: enable / disable startup_path

### ISSUE THREAD

**Issue by jobevers** [brianbruggeman/ves#1]
I would appreciate an option to enable / disable the `cd startup_path` line in .vshrc.

There are times where I want to run a script on some data that is outside of my repo and it would be nice to be able to do:

```
cd ~/mydata
vsh myvenv python ~/myrepo/scripts/process.py datafile1
```

**Comment by brianbruggeman** [comment]
Wow - I'm sorry I haven't seen this.

Definitely going to put this in when I get a chance.  Thanks!

**Comment by brianbruggeman** [comment]
I've modified how the working path works in 0.7.x.
1.  There's a configuration file ~/.vsh/<venv_name>.cfg which holds configuration data, including a working path.

2.  When generating a new virtual environment, you can choose to add a commandline option, `-w` which will set the working path for subsequent commands within the virtual environment:
    
     `vsh -w <working_path> <venv_name> ...`

3.  If `-w` is not used then the configuration will not save any working path and the subsequent commands will be run with a working path of CWD.

4.  If `-w` was previously set and you want to ignore that working path, you can choose to use the `-W` flag which will ignore the working path stored within the configuration file.

5.  Finally, if you forgot to add the -w option in the initial creation, or you want to change the working path, a subsequent `-w` later will set the configuration.

Please let me know if those changes address your concern.

**Comment by jobevers** [comment]
Sounds good to me.
